### ISSUE TITLE
convert gk2a files to latlon projection

### ISSUE THREAD

**Issue by MilesSowden** [cardat/air-health-bushfire-smoke-controller#1]
Nothing is working see the four gk2a files added. the code must quickly extract all variables in a file and convert it to latlon projection.

**Comment by MilesSowden** [comment]
Hi Andrew, Ivan asked that you include the issues in your task management

**Comment by ivanhanigan** [comment]
@ivanhanigan I will follow up with @bushtecho

**Comment by ivanhanigan** [comment]
@MilesSowden I can look into this now but I think I need more info about what the issues are.

**Comment by ivanhanigan** [comment]
@bushtecho @cassandrayuen and @MilesSowden this was discussed today and we agree that it is needed but not sure of the priority.  I think if Cass works on the controller for the blending of the GLC first I will be happy and then come to this with Miles.

**Comment by MilesSowden** [comment]
@bushtecho @cassandrayuen @ivanhanigan can we add this to tomorrow's agenda? Is it not simpler to ask Jeremy for his python codes to do it rather than reinventing stuff?

**Comment by ivanhanigan** [comment]
Closed as we wont get to use gk2a this time
