### ISSUE TITLE
Ivan FYI early version sparse CSV2netCDF grid

### ISSUE THREAD

**Issue by MilesSowden** [cardat/air-health-bushfire-smoke-controller#2]
@ivanhanigan added you here if you wish to provide feedback comments on improvements. I will be working on this over the weekend. This is simply code modified from internet searches and may have multiple issues/debugging.

**Comment by ivanhanigan** [comment]
@MilesSowden what CSV are you aiming for? is it this one [au_aeronet_hourly.csv](https://github.com/cardat/air-health-bushfire-smoke-controller/blob/main/au_aeronet_hourly.csv)?

**Comment by MilesSowden** [comment]
@ivanhanigan,  That was an earlier export from Excel with YYYY MM DD HH I'm thinking of a more simpler XYT_Parameters file as in
"csv2netCDF example of typical input file" (Noting that that file is TXY

**Comment by MilesSowden** [comment]
@ivanhanigan This is a follow-up from last week's meeting. 

Kriging in it's various forms, assumes that distance is the only factor affecting air pollution levels and does not account for other factors such as topography and meteorology that can significantly influence the dispersion of air pollutants, especially in the case of smoke plumes that may not be detected by monitoring sites. Modeling errors typically arise from errors in wind speed (timing) or direction (space). 

In short, GLCs provide accurate surface concentrations at the monitoring sites, AOD provides spatiotemporal resolution, and modeling provides a predictive concentration across the grid that may require spatially and temporally correcting or calibrating to improve accuracy. By blending and integrating these different data sources, a more comprehensive and accurate representation of air quality can be produced to inform effective mitigation strategies and interventions.

Furthermore, the final output of the blending should be in a netCDF format to facilitate easy comparisons between GLCs, AOD, and CTM as per project specifications. There is merit in producing the GLC data as netCDF files simply to match the format of the other input sources, ensuring consistency, and allowing for better data analysis and interpretation.

**Comment by ivanhanigan** [comment]
@MilesSowden great summary thanks.  We can adjust CTM by modelling the error surface using kriging and add it back on. A common term for this is residual kriging, and is the basis of the theory behind [Universal Kriging](https://pro.arcgis.com/en/pro-app/latest/help/analysis/geostatistical-analyst/understanding-universal-kriging.htm)

Your point about netCDF format is fine. R can write the output of the residual kriging in a netCDF easily.

**Comment by ivanhanigan** [comment]
Closed as we wont get to use aeronet this time

**Comment by ivanhanigan** [comment]
Closed as we wont get to use aeronet this time
