### ISSUE TITLE
getdata.sh settings

### ISSUE THREAD

**Issue by ivanhanigan** [cardat/air-health-bushfire-smoke-controller#3]
@MilesSowden I added the [getdata.sh](https://github.com/cardat/air-health-bushfire-smoke-controller/blob/main/getdata.sh) because I am going to add a bit to grab the GLC monitor obs there and so the inbox will have the GLC prepared before the blending module is run

**Comment by ivanhanigan** [comment]
@MilesSowden I have now put in an R script to prepare the observations of PM2.5 from ground level (GLC) using the NAPMD.  The API is not responding at the present time so we will go with the PostGIS server.

**Comment by ivanhanigan** [comment]
done GLC

**Comment by MilesSowden** [comment]
@ivanhanigan , 
1: can you please provide the name of the R script that needs to be run for the PM2.5 observations from GLC?
2: should we create a separate new issue for the failure of the API to run since it needs to work for the final CSIRO code to be functional?
3: thanks for letting us know you copied getdata.sh over. Should we keep this issue open to add AERONET and GK2A to getdata.sh for future modifications?

**Comment by ivanhanigan** [comment]
@MilesSowden Re 1. the R script for GLC.  the GLC datasets are downloaded in 'run-once' R codes and stored at the following locations in sqlite databases.

```
/hdd/projects/AQFx/glc_aqvx/glc_aqvx.sqlite
/hdd/projects/AQFx/glc_napmd/glc_napmd.sqlite
```

These can easily be extracted using R database connector `DBI`

```
if(!require('DBI')) install.packages('DBI'); library(DBI)
ch <- dbConnect(RSQLite::SQLite(), "/hdd/projects/AQFx/glc_aqvx/glc_aqvx.sqlite")
dat <- dbGetQuery(ch, "SELECT * FROM glc_aqvx where yy = '2019' and mm = '09' and dd = '01' and hh = '01'")
```

I believe @cassandrayuen is planning to integrate such R code into her work that builds the kriging of GLC.

Re 2. yes the fact the API can fail occasionally will be an issue in the production environment and should be a new issue.

Re 3. we may work toward AERONET soon and yes let's keep it open

**Comment by ivanhanigan** [comment]
we won't work toward AERONET soon so closing this
