### ISSUE TITLE
New folder for blending pipeline

### ISSUE THREAD

**Issue by ivanhanigan** [cardat/air-health-bushfire-smoke-controller#5]
@MilesSowden I have moved these as they are not part of CarFireSmoke

```
 air-health-bushfire-smoke-blending
 air-health-bushfire-smoke-controller
```

Now at `/hdd/projects` instead

**Comment by ivanhanigan** [comment]
THis is complete and `getdata.sh` is working as expected into the new location

**Comment by MilesSowden** [comment]
@ivanhanigan , noted
