### ISSUE TITLE
qc: for deepdive compare to AQVx to NAPMD hourly PM2.5 data

### ISSUE THREAD

**Issue by ivanhanigan** [cardat/air-health-bushfire-smoke-controller#6]
can we re-write the API targets?

**Comment by ivanhanigan** [comment]
what time variable are we using? UTC? local?

**Comment by ivanhanigan** [comment]
also do the daily for the states that don't have hourly in the NAPMD

**Comment by ivanhanigan** [comment]
@cassandrayuen just got hourly. it does have all states in it thankfully.  I stored at "/hdd/projects/AQFx/glc_napmd/glc_napmd.sqlite"

**Comment by ivanhanigan** [comment]
Reopened so @cassandrayuen can report on the comparison between NAPMD and AQVx here

**Comment by MilesSowden** [comment]
@ivanhanigan,  it's important to consider the time zone and daylight savings implications in our project. To clarify, Himawari, CSIRO, and CAMS use UTC for their time zones and do not adjust for daylight savings. Additionally, it's important to note that Himawari is geostationary in respect to the WA time zone, which means that our UTC time matches the sunrise/sunset times, etc. Time zones are crucial and easily checked to ensure that the output matches solar radiation and temperatures.

**Comment by cassandrayuen** [comment]
Hourly observations of SA and NT in NAPMD are in UTC+9.5 (ACST) - will force a UTC+9 timezone on the timestamps to match to the on-the-hour CSIRO and CAMS UTC times. Unless there is another option?

**Comment by ivanhanigan** [comment]
@cassandrayuen  thanks I cannot thi k of any other option at this time. Thanks

**Comment by ivanhanigan** [comment]
not doing this one as we can trust AQVx API data here
