### ISSUE TITLE
stepwise: code a step by step tool (in R)

### ISSUE THREAD

**Issue by ivanhanigan** [cardat/air-health-bushfire-smoke-controller#7]
write a tool in R as discussed to step thru each time of the deep dive and PREPARE the inbox for the blender

**Comment by ivanhanigan** [comment]
this is more detail

Ivan wanted to write a tool in R as discussed to step thru each time of the deep dive and PREPARE the inbox for the blender, rather than a bash script using crontab (e.g. ```Rscript -e "setwd('/hdd/projects/air-health-bushfire-smoke-controller'); if(!require('targets')) install.packages('targets'); targets::tar_make()" ```)

**Comment by MilesSowden** [comment]
@ivanhanigan , it's not R but check out https://github.com/cardat/air-health-bushfire-smoke-controller/blob/main/run_deepdive.sh which does the same thing.  You can add any routines by line 18 that need to get called. If you need to step through by hourly then it's simply a change of the temporal increment

**Comment by ivanhanigan** [comment]
Thanks. I will check it out

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
